[package]
name = "rustris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
env_logger = "0.10"
find_folder = "0.3.0"
log = "0.4"
piston2d-opengl_graphics = "0.82.0"
piston_window = "0.127"
rand = "0.8"
rand_xoshiro = "0.6"
strum = { version = "0.24", features = ["derive"] }
vecmath = "1"
