[package]
name = "rustris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
env_logger = "0.10.0"
log = "0.4.17"
piston_window = "0.127.0"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
strum = { version = "0.24.1", features = ["derive"] }
vecmath = "1.0.0"
